# **EDA NOTEBOOK**

## Objectives

* Perform Exploratory Data Analysis on the cleaned Telco customer churn dadtaset to understand the dataset structure

## Inputs

* Cleaned Telco customer churn dataset - Telco-Customer-Churn-Cleaned.csv 

## Outputs

* Summary statistics and notes regarding values

## Additional Comments

* These findings will aid feature engineering and modelling steps later in the project.

## Statistical Foundations

Understanding basic statistical concepts is important for analysing datasets and building machine learning models. The following concepts support the analysis performed in this project.

**Mean** - The mean (average) is the sum of all values divided by the number of observations.

Formula:

Mean = (x₁ + x₂ + x₃ + ... + xₙ) / n

In this project, the mean helps understand the average monthly charges or tenure of customers in the dataset.

 **Median** - The median is the middle value in a dataset when the values are arranged in ascending order.

* If the number of observations is odd, the median is the middle value.
* If it is even, the median is the average of the two middle values.

The median is useful because it reduces the impact of outliers compared to the mean.

Example in this dataset: Median MonthlyCharges helps identify the typical cost paid by customers.

**Standard Deviation** - The standard deviation measures how spread out the values in a dataset are around the mean.

Formula:

σ = √( Σ (x - μ)² / N )

Where:
x = data value
μ = mean
N = number of observations

A high standard deviation means the values vary widely, while a low standard deviation means the values are close to the mean.

In this project, it helps measure variation in:
Monthly charges
Total charges
Customer tenure

---

## Probability

Probability measures the likelihood that an event will occur.

Formula:

Probability = Number of favourable outcomes / Total number of outcomes

In this project, probability is used when predicting customer churn likelihood using the machine learning model.

For example:
P(Churn = Yes)
represents the probability that a customer will leave the service.

---

## Hypothesis Testing

Hypothesis testing is used to determine whether a statistical assumption about a dataset is likely to be true.

It involves two hypotheses:

**Null Hypothesis (H₀)**
There is no relationship between variables.

**Alternative Hypothesis (H₁)**
There is a significant relationship between variables.

Example in churn analysis, hypothesis can claim that:
* H₀: Contract type has no effect on customer churn.
* H₁: Contract type affects customer churn.

Through data analysis and visualisation, we evaluate whether patterns suggest rejecting the null hypothesis. 


Hypothesis testing helps determine whether patterns observed in the data are meaningful or simply due to random chance.

1. **P-Value**

A p-value is a statistical measure used to determine the significance of results. It ranges between 0 and 1.

Typical interpretation:
* p < 0.05 → statistically significant, reject the null hypothesis
* p < 0.01 → highly significant
* p > 0.05 → not statistically significant

In churn analysis, p-values help determine whether variables such as contract type or monthly charges significantly influence churn.

2. **Significance Level**

The significance level (α) is the threshold used to decide whether a result is statistically significant. It is typically set at 0.05 (5%).

If:
* p-value < significance level, the null hypothesis is rejected.
* p-value > significance level, the null hypothesis cannot be rejected.

##### Hypothesis Tests Used in Data Analysis

Several statistical tests can be used to validate hypotheses.

* **Welch’s T-Test** 

A Welch’s T-test is used to compare the means of two groups to determine whether they are statistically different.

Unlike a standard t-test, the Welch test does not assume equal variance or equal sample sizes, making it more flexible.
For example, it could be used to compare:
Average monthly charges of churned vs non-churned customers

* **Chi-Square Test**

The Chi-Square test is used to analyse categorical data and determine whether there is a relationship between variables.

In this project it could be used to evaluate relationships such as:
- Contract type vs churn
- Internet service vs churn
The test compares observed values with expected values if the null hypothesis were true.

* **ANOVA (Analysis of Variance)**

ANOVA is used to compare the means of three or more groups to determine if there are statistically significant differences between them.

For example, ANOVA could be used to compare:
Average monthly charges across different contract types

The purpose is to determine whether differences are real or simply due to random chance.

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'/Users/isaacola/Documents/vscode-project/Telco_Customer_Churn/Telco-Customer-Churn/Research'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'/Users/isaacola/Documents/vscode-project/Telco_Customer_Churn/Telco-Customer-Churn'

# Explorative Data Analysis

In [4]:
# Import Libraries

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Load Cleaned Dataset
df = pd.read_csv("dataset/processed/Telco-Customer-Churn-Cleaned.csv")
print("Dataset loaded successfully.")

Dataset loaded successfully.

In [6]:
#  Data Overview
print("First five rows:")
df.head()

First five rows:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group
0,7590-VHVEG,Female,0,1,0,1,0,No phone service,DSL,No,...,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0,0-1yr
1,5575-GNVDE,Male,0,0,0,34,1,No,DSL,Yes,...,No,No,No,One year,0,Mailed check,56.95,1889.50,0,2-4yr
2,3668-QPYBK,Male,0,0,0,2,1,No,DSL,Yes,...,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1,0-1yr
3,7795-CFOCW,Male,0,0,0,45,0,No phone service,DSL,Yes,...,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0,2-4yr
4,9237-HQITU,Female,0,0,0,2,1,No,Fiber optic,No,...,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1,0-1yr

In [7]:
# Display DataFrame info
print("Dataframe info:")
df.info()

Dataframe info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   int64
 4   Dependents        7032 non-null   int64
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   int64
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   int64
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   int64
 21  tenure_group      7032 non-null   object
dtypes: float64(2), int64(7), object(13)
memory usage: 1.2+ MB

In [8]:
# Statistical summary
df.describe(include="all")

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group
count,7032,7032,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032,7032,7032,...,7032,7032,7032,7032,7032.000000,7032,7032.000000,7032.000000,7032.000000,7032
unique,7032,2,NaN,NaN,NaN,NaN,NaN,3,3,3,...,3,3,3,3,NaN,4,NaN,NaN,NaN,5
top,7590-VHVEG,Male,NaN,NaN,NaN,NaN,NaN,No,Fiber optic,No,...,No,No,No,Month-to-month,NaN,Electronic check,NaN,NaN,NaN,0-1yr
freq,1,3549,NaN,NaN,NaN,NaN,NaN,3385,3096,3497,...,3472,2809,2781,3875,NaN,2365,NaN,NaN,NaN,2175
mean,NaN,NaN,0.162400,0.482509,0.298493,32.421786,0.903299,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.592719,NaN,64.798208,2283.300441,0.265785,NaN
std,NaN,NaN,0.368844,0.499729,0.457629,24.545260,0.295571,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.491363,NaN,30.085974,2266.771362,0.441782,NaN
min,NaN,NaN,0.000000,0.000000,0.000000,1.000000,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,NaN,18.250000,18.800000,0.000000,NaN
25%,NaN,NaN,0.000000,0.000000,0.000000,9.000000,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,NaN,35.587500,401.450000,0.000000,NaN
50%,NaN,NaN,0.000000,0.000000,0.000000,29.000000,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.000000,NaN,70.350000,1397.475000,0.000000,NaN
75%,NaN,NaN,0.000000,1.000000,1.000000,55.000000,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.000000,NaN,89.862500,3794.737500,1.000000,NaN
max,NaN,NaN,1.000000,1.000000,1.000000,72.000000,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.000000,NaN,118.750000,8684.800000,1.000000,NaN

In [10]:
# Check target variable distribution
df["Churn"].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

---